import { WorkoutTag } from './workout-tags';

export type StatType = 'strength' | 'cardio' | 'flexibility' | 'agility' | 'mind';

export const TAG_STATS_WEIGHTS: Record<WorkoutTag, Partial<Record<StatType, number>>> = {
  // Training Styles
  'CrossFit': { strength: 0.4, cardio: 0.4, agility: 0.2 },
  'Hyrox': { strength: 0.4, cardio: 0.5, agility: 0.1 },
  'Calisthenics': { strength: 0.6, agility: 0.3, flexibility: 0.1 },
  'Bodybuilding': { strength: 1.0 },
  'Powerlifting': { strength: 1.0 },
  'Strongman': { strength: 0.9, cardio: 0.1 },
  'Olympic Weightlifting': { strength: 0.7, agility: 0.3 },
  'Functional Training': { strength: 0.5, agility: 0.3, cardio: 0.2 },
  'HIIT': { cardio: 0.8, strength: 0.2 },
  'LISS': { cardio: 1.0 },
  'Tabata': { cardio: 0.9, strength: 0.1 },
  'EMOM': { cardio: 0.6, strength: 0.4 },
  'AMRAP': { cardio: 0.7, strength: 0.3 },
  'For Time': { cardio: 0.7, strength: 0.3 },
  'Circuit Training': { cardio: 0.6, strength: 0.4 },
  'Interval Training': { cardio: 0.9, strength: 0.1 },
  'Fartlek': { cardio: 1.0 },
  'Plyometrics': { agility: 0.8, strength: 0.2 },
  'Isometrics': { strength: 0.8, mind: 0.2 },
  'Tempo Training': { strength: 0.9, mind: 0.1 },
  'Drop Sets': { strength: 1.0 },
  'Supersets': { strength: 0.8, cardio: 0.2 },
  'Cluster Sets': { strength: 1.0 },
  'GVT': { strength: 1.0 },

  // Activities
  'Running': { cardio: 1.0 },
  'Sprinting': { cardio: 0.6, strength: 0.2, agility: 0.2 },
  'Jogging': { cardio: 1.0 },
  'Trail Running': { cardio: 0.8, agility: 0.2 },
  'Cycling': { cardio: 1.0 },
  'Spinning': { cardio: 1.0 },
  'Mountain Biking': { cardio: 0.7, agility: 0.3 },
  'Swimming': { cardio: 0.8, strength: 0.2 },
  'Rowing': { cardio: 0.7, strength: 0.3 },
  'Jump Rope': { cardio: 0.7, agility: 0.3 },
  'Boxing': { cardio: 0.5, agility: 0.3, strength: 0.2 },
  'Kickboxing': { cardio: 0.5, agility: 0.3, strength: 0.2 },
  'Muay Thai': { strength: 0.4, agility: 0.3, cardio: 0.3 },
  'MMA': { strength: 0.4, agility: 0.3, cardio: 0.3 },
  'Jiu Jitsu': { strength: 0.3, agility: 0.4, mind: 0.3 },
  'Wrestling': { strength: 0.6, cardio: 0.4 },
  'Yoga': { flexibility: 0.6, mind: 0.3, strength: 0.1 },
  'Vinyasa': { flexibility: 0.5, strength: 0.3, mind: 0.2 },
  'Hatha': { flexibility: 0.6, mind: 0.4 },
  'Bikram': { flexibility: 0.7, cardio: 0.3 },
  'Pilates': { flexibility: 0.4, strength: 0.4, mind: 0.2 },
  'Barre': { flexibility: 0.5, strength: 0.3, agility: 0.2 },
  'Dance': { agility: 0.6, cardio: 0.4 },
  'Zumba': { cardio: 0.7, agility: 0.3 },
  'Hiking': { cardio: 0.9, mind: 0.1 },
  'Rucking': { cardio: 0.6, strength: 0.4 },
  'Climbing': { strength: 0.6, flexibility: 0.2, mind: 0.2 },
  'Bouldering': { strength: 0.7, agility: 0.2, mind: 0.1 },
  'Obstacle Course': { agility: 0.4, strength: 0.3, cardio: 0.3 },

  // Focus Areas (Usually act as modifiers or reinforcements)
  'Full Body': { strength: 0.5, cardio: 0.5 },
  'Upper Body': { strength: 1.0 },
  'Lower Body': { strength: 1.0 },
  'Push': { strength: 1.0 },
  'Pull': { strength: 1.0 },
  'Legs': { strength: 1.0 },
  'Chest': { strength: 1.0 },
  'Back': { strength: 1.0 },
  'Shoulders': { strength: 1.0 },
  'Arms': { strength: 1.0 },
  'Biceps': { strength: 1.0 },
  'Triceps': { strength: 1.0 },
  'Abs': { strength: 0.7, agility: 0.3 },
  'Core': { strength: 0.7, agility: 0.3 },
  'Glutes': { strength: 1.0 },
  'Quads': { strength: 1.0 },
  'Hamstrings': { strength: 1.0 },
  'Calves': { strength: 1.0 },

  // Goals
  'Strength': { strength: 1.0 },
  'Hypertrophy': { strength: 1.0 },
  'Endurance': { cardio: 1.0 },
  'Stamina': { cardio: 1.0 },
  'Power': { strength: 0.7, agility: 0.3 },
  'Explosiveness': { agility: 0.6, strength: 0.4 },
  'Speed': { agility: 0.7, cardio: 0.3 },
  'Agility': { agility: 1.0 },
  'Balance': { agility: 0.6, mind: 0.4 },
  'Coordination': { agility: 0.8, mind: 0.2 },
  'Flexibility': { flexibility: 1.0 },
  'Mobility': { flexibility: 0.8, mind: 0.2 },
  'Stability': { strength: 0.6, agility: 0.4 },
  'Fat Loss': { cardio: 0.8, strength: 0.2 },
  'Muscle Gain': { strength: 1.0 },
  'Recovery': { mind: 0.5, flexibility: 0.5 },
  'Rehab': { flexibility: 0.5, strength: 0.5 },
  'Warm Up': { cardio: 0.5, flexibility: 0.5 },
  'Cool Down': { flexibility: 0.8, mind: 0.2 },

  // Equipment (Neutral or slight bias)
  'Barbell': { strength: 1.0 },
  'Dumbbell': { strength: 1.0 },
  'Kettlebell': { strength: 0.7, cardio: 0.3 },
  'Machine': { strength: 1.0 },
  'Cable': { strength: 1.0 },
  'Bodyweight': { strength: 0.6, agility: 0.4 },
  'Band': { strength: 0.5, flexibility: 0.5 },
  'TRX': { strength: 0.6, agility: 0.4 },
  'Sandbag': { strength: 0.8, cardio: 0.2 },
  'Medicine Ball': { strength: 0.5, agility: 0.5 },
  'Slam Ball': { strength: 0.5, cardio: 0.5 },
  'Wall Ball': { cardio: 0.6, strength: 0.4 },
  'Box': { agility: 0.7, strength: 0.3 },
  'Rings': { strength: 0.6, agility: 0.4 },
  'Pull Up Bar': { strength: 1.0 },
  'Dip Station': { strength: 1.0 },
  'Rower': { cardio: 0.7, strength: 0.3 },
  'Air Bike': { cardio: 0.9, strength: 0.1 },
  'SkiErg': { cardio: 0.8, strength: 0.2 },
  'Treadmill': { cardio: 1.0 },
  'Elliptical': { cardio: 1.0 },
  'Stairmaster': { cardio: 0.9, strength: 0.1 },

  // Difficulty (Neutral, affects multiplier not distribution)
  'Beginner': {},
  'Intermediate': {},
  'Advanced': {},
  'Elite': {},
  'Scaled': {},
  'Rx': {},

  // Environment (Neutral)
  'Gym': {},
  'Home Workout': {},
  'Outdoor': {},
  'Park': {},
  'Beach': {},
  'Travel': {},
  'Hotel Gym': {},
  'No Equipment': {}
};