export const WORKOUT_TAGS = [
  // Training Styles
  'CrossFit',
  'Hyrox',
  'Calisthenics',
  'Bodybuilding',
  'Powerlifting',
  'Strongman',
  'Halterofilia',
  'Entrenamiento Funcional',
  'HIIT',
  'LISS',
  'Tabata',
  'EMOM',
  'AMRAP',
  'Por Tiempo',
  'Entrenamiento en Circuito',
  'Entrenamiento por Intervalos',
  'Fartlek',
  'Pliometría',
  'Isométricos',
  'Entrenamiento por Tiempo Bajo Tensión',
  'Series Descendentes',
  'Superseries',
  'Series en Grupo',
  'GVT',
  
  // Activities
  'Carrera',
  'Sprints',
  'Trote',
  'Trail Running',
  'Ciclismo',
  'Spinning',
  'Mountain Bike',
  'Natación',
  'Remo',
  'Comba',
  'Boxing',
  'Kickboxing',
  'Muay Thai',
  'MMA',
  'Jiu Jitsu',
  'Wrestling',
  'Yoga',
  'Vinyasa',
  'Hatha',
  'Bikram',
  'Pilates',
  'Barre',
  'Danza',
  'Zumba',
  'Senderismo',
  'Rucking',
  'Escalada',
  'Bouldering',
  'Carrera de Obstáculos',
  
  // Focus Areas
  'Cuerpo Completo',
  'Tren Superior',
  'Tren Inferior',
  'Empuje',
  'Tracción',
  'Piernas',
  'Pecho',
  'Espalda',
  'Hombros',
  'Brazos',
  'Bíceps',
  'Tríceps',
  'Abdominales',
  'Core',
  'Glúteos',
  'Cuádriceps',
  'Isquios',
  'Gemelos',
  
  // Goals
  'Fuerza',
  'Hipertrofia',
  'Resistencia',
  'Fondo',
  'Potencia',
  'Explosividad',
  'Velocidad',
  'Agilidad',
  'Equilibrio',
  'Coordinación',
  'Flexibilidad',
  'Movilidad',
  'Estabilidad',
  'Pérdida de Grasa',
  'Ganancia Muscular',
  'Recuperación',
  'Rehabilitación',
  'Calentamiento',
  'Vuelta a la Calma',
  
  // Equipment
  'Barbell',
  'Dumbbell',
  'Kettlebell',
  'Máquina',
  'Polea',
  'Peso Corporal',
  'Goma',
  'TRX',
  'Costal',
  'Balón Medicinal',
  'Balón de Slam',
  'Wall Ball',
  'Cajón',
  'Anillas',
  'Barra de Dominadas',
  'Paralelas',
  'Remo',
  'Air Bike',
  'SkiErg',
  'Cinta',
  'Elíptica',
  'Escaladora',
  
  // Difficulty/Level
  'Principiante',
  'Intermedio',
  'Avanzado',
  'Élite',
  'Escalado',
  'Rx',
  
  // Environment
  'Gimnasio',
  'Casa',
  'Exterior',
  'Parque',
  'Playa',
  'Viaje',
  'Gimnasio Hotel',
  'Sin Material'
] as const;

export type WorkoutTag = typeof WORKOUT_TAGS[number];
