import { WorkoutTag } from './workout-tags'

// Mismo catálogo que src/constants/tag-stats.ts (apps/web, ahora migrado
// acá) — pondera cuánto aporta cada tag a cada stat RPG del workout. Lo usa
// computeWorkoutStats (./rewards.ts) para repartir el XP de un workout entre
// sus stats al guardarlo, y como fallback de display para workouts viejos
// que no tienen `stats` persistido todavía.
export type StatType = 'strength' | 'cardio' | 'flexibility' | 'agility' | 'mind'

export const TAG_STATS_WEIGHTS: Record<WorkoutTag, Partial<Record<StatType, number>>> = {
  // Training Styles
  'CrossFit': { strength: 0.4, cardio: 0.4, agility: 0.2 },
  'Hyrox': { strength: 0.4, cardio: 0.5, agility: 0.1 },
  'Calisthenics': { strength: 0.6, agility: 0.3, flexibility: 0.1 },
  'Bodybuilding': { strength: 1.0 },
  'Powerlifting': { strength: 1.0 },
  'Strongman': { strength: 0.9, cardio: 0.1 },
  'Halterofilia': { strength: 0.7, agility: 0.3 },
  'Entrenamiento Funcional': { strength: 0.5, agility: 0.3, cardio: 0.2 },
  'Militar': { strength: 0.3, cardio: 0.4, agility: 0.3 },
  'HIIT': { cardio: 0.8, strength: 0.2 },
  'LISS': { cardio: 1.0 },
  'Tabata': { cardio: 0.9, strength: 0.1 },
  'EMOM': { cardio: 0.6, strength: 0.4 },
  'AMRAP': { cardio: 0.7, strength: 0.3 },
  'Por Tiempo': { cardio: 0.7, strength: 0.3 },
  'Entrenamiento en Circuito': { cardio: 0.6, strength: 0.4 },
  'Entrenamiento por Intervalos': { cardio: 0.9, strength: 0.1 },
  'Fartlek': { cardio: 1.0 },
  'Pliometría': { agility: 0.8, strength: 0.2 },
  'Isométricos': { strength: 0.8, mind: 0.2 },
  'Entrenamiento por Tiempo Bajo Tensión': { strength: 0.9, mind: 0.1 },
  'Series Descendentes': { strength: 1.0 },
  'Superseries': { strength: 0.8, cardio: 0.2 },
  'Series en Grupo': { strength: 1.0 },
  'GVT': { strength: 1.0 },

  // Activities
  'Carrera': { cardio: 1.0 },
  'Sprints': { cardio: 0.6, strength: 0.2, agility: 0.2 },
  'Trote': { cardio: 1.0 },
  'Trail Running': { cardio: 0.8, agility: 0.2 },
  'Ciclismo': { cardio: 1.0 },
  'Spinning': { cardio: 1.0 },
  'Mountain Bike': { cardio: 0.7, agility: 0.3 },
  'Natación': { cardio: 0.8, strength: 0.2 },
  'Remo': { cardio: 0.7, strength: 0.3 },
  'Comba': { cardio: 0.7, agility: 0.3 },
  'Boxing': { cardio: 0.5, agility: 0.3, strength: 0.2 },
  'Kickboxing': { cardio: 0.5, agility: 0.3, strength: 0.2 },
  'Muay Thai': { strength: 0.4, agility: 0.3, cardio: 0.3 },
  'MMA': { strength: 0.4, agility: 0.3, cardio: 0.3 },
  'Jiu Jitsu': { strength: 0.3, agility: 0.4, mind: 0.3 },
  'Wrestling': { strength: 0.6, cardio: 0.4 },
  'Yoga': { flexibility: 0.6, mind: 0.3, strength: 0.1 },
  'Vinyasa': { flexibility: 0.5, strength: 0.3, mind: 0.2 },
  'Hatha': { flexibility: 0.6, mind: 0.4 },
  'Bikram': { flexibility: 0.7, cardio: 0.3 },
  'Pilates': { flexibility: 0.4, strength: 0.4, mind: 0.2 },
  'Barre': { flexibility: 0.5, strength: 0.3, agility: 0.2 },
  'Danza': { agility: 0.6, cardio: 0.4 },
  'Zumba': { cardio: 0.7, agility: 0.3 },
  'Senderismo': { cardio: 0.9, mind: 0.1 },
  'Rucking': { cardio: 0.6, strength: 0.4 },
  'Escalada': { strength: 0.6, flexibility: 0.2, mind: 0.2 },
  'Bouldering': { strength: 0.7, agility: 0.2, mind: 0.1 },
  'Carrera de Obstáculos': { agility: 0.4, strength: 0.3, cardio: 0.3 },

  // Focus Areas (Usually act as modifiers or reinforcements)
  'Cuerpo Completo': { strength: 0.5, cardio: 0.5 },
  'Tren Superior': { strength: 1.0 },
  'Tren Inferior': { strength: 1.0 },
  'Empuje': { strength: 1.0 },
  'Tracción': { strength: 1.0 },
  'Piernas': { strength: 1.0 },
  'Pecho': { strength: 1.0 },
  'Espalda': { strength: 1.0 },
  'Hombros': { strength: 1.0 },
  'Brazos': { strength: 1.0 },
  'Bíceps': { strength: 1.0 },
  'Tríceps': { strength: 1.0 },
  'Abdominales': { strength: 0.7, agility: 0.3 },
  'Core': { strength: 0.7, agility: 0.3 },
  'Glúteos': { strength: 1.0 },
  'Cuádriceps': { strength: 1.0 },
  'Isquios': { strength: 1.0 },
  'Gemelos': { strength: 1.0 },

  // Goals
  'Fuerza': { strength: 1.0 },
  'Hipertrofia': { strength: 1.0 },
  'Resistencia': { cardio: 1.0 },
  'Fondo': { cardio: 1.0 },
  'Potencia': { strength: 0.7, agility: 0.3 },
  'Explosividad': { agility: 0.6, strength: 0.4 },
  'Velocidad': { agility: 0.7, cardio: 0.3 },
  'Agilidad': { agility: 1.0 },
  'Equilibrio': { agility: 0.6, mind: 0.4 },
  'Coordinación': { agility: 0.8, mind: 0.2 },
  'Flexibilidad': { flexibility: 1.0 },
  'Movilidad': { flexibility: 0.8, mind: 0.2 },
  'Estabilidad': { strength: 0.6, agility: 0.4 },
  'Pérdida de Grasa': { cardio: 0.8, strength: 0.2 },
  'Ganancia Muscular': { strength: 1.0 },
  'Recuperación': { mind: 0.5, flexibility: 0.5 },
  'Rehabilitación': { flexibility: 0.5, strength: 0.5 },
  'Calentamiento': { cardio: 0.5, flexibility: 0.5 },
  'Vuelta a la Calma': { flexibility: 0.8, mind: 0.2 },

  // Equipment (Neutral or slight bias)
  'Barbell': { strength: 1.0 },
  'Dumbbell': { strength: 1.0 },
  'Kettlebell': { strength: 0.7, cardio: 0.3 },
  'Máquina': { strength: 1.0 },
  'Polea': { strength: 1.0 },
  'Peso Corporal': { strength: 0.6, agility: 0.4 },
  'Goma': { strength: 0.5, flexibility: 0.5 },
  'TRX': { strength: 0.6, agility: 0.4 },
  'Costal': { strength: 0.8, cardio: 0.2 },
  'Balón Medicinal': { strength: 0.5, agility: 0.5 },
  'Balón de Slam': { strength: 0.5, cardio: 0.5 },
  'Wall Ball': { cardio: 0.6, strength: 0.4 },
  'Cajón': { agility: 0.7, strength: 0.3 },
  'Anillas': { strength: 0.6, agility: 0.4 },
  'Barra de Dominadas': { strength: 1.0 },
  'Paralelas': { strength: 1.0 },
  'Air Bike': { cardio: 0.9, strength: 0.1 },
  'SkiErg': { cardio: 0.8, strength: 0.2 },
  'Cinta': { cardio: 1.0 },
  'Elíptica': { cardio: 1.0 },
  'Escaladora': { cardio: 0.9, strength: 0.1 },

  // Difficulty (Neutral, affects multiplier not distribution)
  'Principiante': {},
  'Intermedio': {},
  'Avanzado': {},
  'Élite': {},
  'Escalado': {},
  'Rx': {},

  // Environment (Neutral)
  'Gimnasio': {},
  'Casa': {},
  'Exterior': {},
  'Parque': {},
  'Playa': {},
  'Viaje': {},
  'Gimnasio Hotel': {},
  'Sin Material': {},
}
